<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />

    <link type="text/css" href="/css/portal.css" rel="stylesheet" />

    <script type="text/javascript" src="/js/jui/js/jquery-1.4.4.min.js"></script>
    <script type="text/javascript" src="/js/jui/js/jquery-ui-1.8.9.custom.min.js"></script>
    <script type="text/javascript" src="/js/portal.js"></script>

</head>


<div align="center" width="80%">

    <div style="border: solid gray; margin: 50px;">
        <form action="/portal/index/consulta" method="post" class="" id='form1'>

            <h2>Entre com os critérios de pesquisa</h2> 

            <div style="text-align: left; border: transparent; width: 380px; ">
		Ex:  macarrão, massa verde, "Macarronada da Tia Dalva"
		<br>
		Ex: catupiri, bacon, peito de peru
            </div>

            <br>
            <input type="textarea" name="criterio" style="width: 400px;" value="<?php echo $this->pesquisa_facapedido_criterio; ?>">
            <br>
            <br>
            Tipos de produtos:
            <br><br>

            <div style="width:450; height: 100;">
		<?php
		//formData2 eh um array comecando do indice 0 e contendo os codigos de tipos de produtos que a empresa trabalha
		//cod_tipo_produto é um array cujo indices sao os cod_tipo_produto e o conteudo o nome do tipo. Contem todos os tipos produtos existentes.
		$i = 0;
		foreach (array_keys($this->cod_tipo_produto) as $cod_tipo_produto)
		{
		    $checked = " ";
		    if (!empty($this->pesquisa_facapedido_tipo_produto) && in_array($cod_tipo_produto, $this->pesquisa_facapedido_tipo_produto))
		    {
			$checked = "checked";
		    }
		?>
    		<input  type="checkbox" name="cod_tipo_produto[]" <?php echo $checked; ?> value="<?php echo $cod_tipo_produto ?>" class=""> <?php echo $this->cod_tipo_produto[$cod_tipo_produto] ?>

		<?php } ?>
	    </div>

	    Caloria < que: <input type="text" name="caloria" style="width:50" value="<?php echo $this->pesquisa_facapedido_caloria; ?>">



	    <br><br><br>
            <input type="submit" value="Pesquisar">

        </form>
    </div>

</div>



<?php
		for ($i = 0; $i < sizeof($this->resultado); $i++)
		//foreach ((array) $this->resultado as $hit)
		{
		    //$hit = $this->resultado->fetch(PDO::FETCH_ASSOC);


		    echo "<div style=' clear:both; margin: 80px; color:black;' > \n";
		    echo "<div style='float: left; margin: 20px 1px 20px 21px; width:200px;'><p><img src='/portal/index/get-Imagem-Produto/id/" . $this->resultado[$i]['cod_foto'] . "' width='141' height='auto' alt=''> </p> </div> \n";
		    echo "<div style='float: left; margin: 50px 1px 20px 21px; width:100px; font-size: large;'> <p style='display: block' > \n";
		    echo $this->resultado[$i]["nome"];
		    echo "</p> </div> <!-- nome do produto --> \n";
		    echo "<div style='float: left; margin: 60px 1px 20px 80px; width:150px; font-size: medium;'> \n";
		    echo $this->resultado[$i]["nome_empresa"];
		    echo "</div> <!-- nome da empresa --> \n";
		    //imprime os tamanhos disponiveis e precos do produto
		    echo "<div style='float: left; margin: 60px 1px 20px 80px; width:200px; font-size: medium;'> \n";
		    if (!empty($this->resultado[$i]['preco_promocional']))
		    {
			echo ($this->resultado[$i]['tamanho']."=> De ");
			echo $this->resultado[$i]["preco"];
			echo (" por ");
			echo $this->resultado[$i]["preco_promocional"];
		    }
		    else
			echo $this->resultado[$i]['tamanho'] . " => " . $this->resultado[$i]["preco"];

		    $i++;
		    while ($this->resultado[$i]['cod_produto'] == $this->resultado[$i - 1]['cod_produto'])
		    {
			echo "<br> \n";

			if (!empty($this->resultado[$i]['preco_promocional']))
			{
			    echo ($this->resultado[$i]['tamanho']."=> De ");
			    echo $this->resultado[$i]["preco"];
			    echo (" por ");
			    echo $this->resultado[$i]["preco_promocional"];
			}
			else
			    echo $this->resultado[$i]['tamanho'] . " => " . $this->resultado[$i]["preco"];
			$i++;
		    }
		    $i--;
		    echo "</div> <!-- precos -->";

		    //verifica se a empresa esta atendendo nesse horario
		    if ($this->resultado[$i]['isAberto'] == true)
		    {
			echo "<div style='float: left; margin: 60px 1px 20px 21px; width:150px;'> \n";
			echo "<a class='botao_portal_vermelho' target='' title='Ir &agrave; Loja' href='/" . $this->resultado[$i]['url'] . "?cod_produto=" . $this->resultado[$i]['cod_produto'] . "'>" .
			"<span>Ir &agrave; Loja</span></a> </div>";
		    }
		    else
		    {
			$hora_atual = date('H') . ":" . date('i') . ":00";
			echo "<div style='float: left; margin: 60px 1px 20px 21px; width:150px;'> \n";
			echo "<a class='botao_portal_amarelo' target=''	title='Fechada nesse horário' href='#' onclick='lojaFechada(".$this->resultado[$i]['cod_empresa'].",".$this->resultado[$i]['cod_produto'].",".$i. ")'".
			" <span>Fechada nesse horário </span> </a> <span class='msg_estabelecimento_fechado' id='spanFechada".$i."'>Clique no botão se deseja enviar à loja sua vontade ".
			" de que ela estivesse aberta. </span> </div>";
		    }
  
		    echo "</div> \n";
		}
?>


