<h2><?php echo $this->headline; ?></h2>

<div id="tabs" style="width: 714px;">
  <ul>
    <li><a href="#tabs-1">Customizar ingredientes</a></li>
    <li><a href="#tabs-2">Associar categoria a seus ingredientes</a></li>
  </ul>
  <div id="tabs-1">
    <div class="contentForm">

Nesta tela você poderá escolher ingredientes que pretende oferecer como adicionais em seus produtos
e configurá-los de acordo com suas preferências.
    <form action="<?php echo $this->baseUrl()?>/estabelecimento/ingredients/add" method="post" class="frm" id='form1' onsubmit="return validateForm('form1');" enctype="multipart/form-data" >
      <table class="tableFrm" cellspacing="0" cellpadding="0" border="0">
        <tr>
          <td width="70%"><table class="tableFrm" cellspacing="7">
              <tr>
                <td> Ingredientes * </td>
                <td>
                <?php

                if($this->action == 'edit')
                {
                    //apresenta apenas os ingredientes ja customizados
                    $attribs =array("class"=>'input-medium RQR required', 'id'=>'combo_ingrediente', "title"=>'Por favor, indique o ingrediente' ,'style'=>'width:200px','onchange'=>'editaIngrediente(this)');
                    echo $this->formSelect('ingredienteId', $this->formData['cod_ingrediente'], $attribs, $this->ingredienteJaCustomizadoOption);

                }
                else
                {
                    //apresenta apenas os ingredientes nao customizados
                    $attribs =array("class"=>'input-medium RQR required', 'id'=>'combo_ingrediente', "title"=>'Por favor, indique o ingrediente' ,'style'=>'width:200px');
                    echo $this->formSelect('ingredienteId', $this->formData['cod_ingrediente'], $attribs, $this->ingredienteAindaNaoCustomizadoOption);

                }
                
                
             ?>

             <div class='bodyTextSmall'> <span class='tip'></span> <span class='missing'></span></div>

              </td>
              </tr>
              
              <tr>
                <td> Descrição </td>
                <td><input type="text" class="input-medium" maxlength="200"  name="descricao" value="<?php echo $this->formData['descricao']?>" style="width: 200px;">
                  <div class='bodyTextSmall'> <span class='tip'></span> <span class='missing'></span></div></td>
              </tr>
              <tr>
                <td> Preço </td>
                <td>
                <table border="0" cellpadding="0" cellspacing="0" style="margin: 0px; padding: 0px;">
                <tr>
                <td><input type="text" class="input-medium validDecimalNumber"  name="preco_quando_adicional" maxlength="14" value="<?php echo $this->formData['preco_quando_adicional']?>" style="width: 200px;">
                <div class='bodyTextSmall'> <span class='tip'></span> <span class='missing'></span></div>
                </td>
                <td>&nbsp;Preço quando o ingrediente for utilizado como adicional</td>
                </tr>
                </table>

                  </td>
              </tr>
              </table></td>

          <td width="30%">
      
          <?php if(!empty($this->formData['imagem_original'])) {?>
          <span id='image'>
          <img src="<?php echo $this->baseUrl() ?>/estabelecimento/ingredients/get-Image-Original/ingrediente/<?php echo $this->formData['cod_ingrediente']?>" width="151" height="141"  alt="">
           </span><br>
            <span id='changeImage' style="display: none;">
            <input type="file" name="userfile">
            </span>
            <br>
            <span onclick="toggleImage2()" id='labelChangeCancel' style="cursor: pointer; color: maroon;display:none;">Cancela</span>
            <br>
            <span onclick="toggleImage()" id='labelChange' style="cursor: pointer; color: blue;">Trocar</span>
            <span onclick="removeImage()" id='labelRemove' style="cursor: pointer; color: blue;">Remover</span>
            <input type="hidden" value="" name="flagRemoverImagem" id="flagRemoverImagem">

          <?php }

          else if(!empty($this->formData['imagem'])) {
          ?>
          <span id='image'>
          <img src="<?php echo $this->baseUrl() ?>/estabelecimento/ingredients/get-Image/ingrediente/<?php echo $this->formData['cod_ingrediente']?>/empresa/<?php echo $this->formData['cod_empresa']?>" width="151" height="141" alt="">
           </span><br>
            <span id='changeImage' style="display: none;">
            <input type="file" name="userfile">
            </span>
            <br>
            <span onclick="toggleImage2()" id='labelChangeCancel' style="cursor: pointer; color: maroon;display:none;">Cancela</span>
            <br>
            <span onclick="toggleImage()" id='labelChange' style="cursor: pointer; color: blue;">Trocar</span>
            <span onclick="removeImage()" id='labelRemove' style="cursor: pointer; color: blue;">Remover</span>
            <input type="hidden" value="" name="flagRemoverImagem" id="flagRemoverImagem">
         <?php } else {?>
            Logo <br><input type="file" name="userfile">
            <?php }?>

          </td>
        </tr>
      </table>

      <fieldset style=" margin: 0; padding: 0;">
        <legend>Indique em quais categorias este ingrediente se enquadra:</legend>
        <table class="tableFrm" cellspacing="8" cellpadding="0" border="0">
          <tr>
          <?php $i=0;foreach($this->categoriaIngredienteRec as $k=>$v) {
              if(in_array($v['cod_categoria_empresa'],(array)$this->categoriaIngredienteEmpresa)){
                  $checked="checked";
              }else{
                  $checked='';
              }
              ?>
            <td> <input type="checkbox" name="cod_categoria_empresa[]" value="<?php echo $v['cod_categoria_empresa']?>" <?php echo $checked ?>> <?php echo $v['nome']?>   </td>
            <?php if($i>=4){ echo '</tr><tr>';$i=0;}?>
            <?php $i++;}?>
          </tr>


        </table>
      </fieldset>

      <table class="tableFrm" cellspacing="5" cellpadding="0" border="0">
        <tr>
          <td><input type="hidden" name="emorFrom" value="1">
             <input type="hidden" name="action" value="<?php echo $this->action; ?>">
           <input type="hidden" name="cod_empresa" value="<?php echo $this->empresaId?>">
            <input type="submit" name="Save" value="Salvar">
            <input type="button" name="Save" value="Remover" onclick="delIngrediente()">
            <input type="button" name="Save" value="New" onclick="location.href='<?php  echo $this->baseUrl() ?>/estabelecimento/ingredients/'">
            <input type="button" name="Save" value="Lista de ingredientes já customizados" style="margin-left:  400px;" onclick="location.href='<?php echo $this->url(array('controller'=>'ingredients','action'=>'gridView'));?>'"></td>

        </tr>
      </table>
      </form>
    </div>


          <div class="contentForm">
		As categorias permitem organizar grupos de ingredientes que serão oferecidos como adicionais em seus produtos.
Ainda não tem a categoria que precisa? Cadastre uma agora.
      <form action="/estabelecimento/ingredients/add" method="post" class="frm" id='form3' onsubmit="return validateForm('form3');" >
      <fieldset style=" margin: 0; padding: 0;">
	       <legend>Cadastrar categoria:</legend>
        <table class="tableFrm" cellspacing="8" cellpadding="0" border="0">
           <tr>
                <td> Nome </td>

      <td colspan="">
	  <input type="text" name="categoria[nome]" class="RQR required">
              <div class='bodyTextSmall'> <span class='tip'></span> <span class='missing'></span></div>
      </td>

      <td>
         <input type="submit" name="Save" value="Salvar">
      </td>

	   </tr>

        </table>
      </fieldset>
      <table class="tableFrm" cellspacing="5" cellpadding="0" border="0">
        <tr>
          <td><input type="hidden" name="emorFrom" value="3">
	  <input type="hidden" name="ingredienteId" value="<?php echo $this->ingredienteId; ?>">
           <input type="hidden" name="categoria[cod_empresa]" value="<?php echo $this->empresaId?>">
            <input type="hidden" name="cod_empresa" value="<?php echo $this->empresaId?>">

            </td>
        </tr>
      </table>
      </form>
    </div>




  </div>


  <div id="tabs-2">
    <div class="contentForm">

      <form action="<?php echo $this->baseUrl()?>/estabelecimento/ingredients/add" method="post" class="frm" id='form2' onsubmit="return validateForm('form2');" >
      <fieldset style=" margin: 0; padding: 0;">
        <legend>Associar uma categoria aos ingredientes:</legend>
        <table class="tableFrm" cellspacing="8" cellpadding="0" border="0">
           <tr>
                <td> Escolha a categoria * </td>


      <td colspan="10"><?php $attribs =array("class"=>'input-medium RQR required', "title"=>'Por favor, indique Ingredients' ,'style'=>'width:200px','onchange'=>"getCategoria(this,$this->ingredienteId)");
echo $this->formSelect('cod_categoria_empresa', $this->formData['cod_categoria_empresa'], $attribs, $this->categoriaIngredienteOption); ?>
              <div class='bodyTextSmall'> <span class='tip'></span> <span class='missing'></span></div></td>
              </tr>
              
          <tr id="respp">

           
          </tr>
 
        </table>
      </fieldset>
      <table class="tableFrm" cellspacing="5" cellpadding="0" border="0">
        <tr>
          <td><input type="hidden" name="emorFrom" value="2">
              <input type="hidden" name="ingredienteId" value="<?php echo $this->ingredienteId; ?>">
             <input type="hidden" name="action" value="<?php echo $this->action; ?>">
            <input type="hidden" name="cod_empresa" value="<?php echo $this->empresaId?>">
            <input type="submit" name="Save" value="Salvar">
            </td>
        </tr>
      </table>
      </form>
    </div>


      <div class="contentForm">
		As categorias permitem organizar grupos de ingredientes que serão oferecidos como adicionais em seus produtos.
Ainda não tem a categoria que precisa? Cadastre uma agora.
      <form action="/estabelecimento/ingredients/add" method="post" class="frm" id='form4' onsubmit="return validateForm('form4');" >
      <fieldset style=" margin: 0; padding: 0;">
	       <legend>Cadastrar categoria:</legend>
        <table class="tableFrm" cellspacing="8" cellpadding="0" border="0">
           <tr>
                <td> Nome </td>

      <td colspan="">
	  <input type="text" name="categoria[nome]" class="RQR required">
              <div class='bodyTextSmall'> <span class='tip'></span> <span class='missing'></span></div>
      </td>
           
      <td>
         <input type="submit" name="Save" value="Salvar">
      </td>

	   </tr>

        </table>
      </fieldset>
      <table class="tableFrm" cellspacing="5" cellpadding="0" border="0">
        <tr>
          <td><input type="hidden" name="emorFrom" value="4">
	  <input type="hidden" name="ingredienteId" value="<?php echo $this->ingredienteId; ?>">
           <input type="hidden" name="categoria[cod_empresa]" value="<?php echo $this->empresaId?>">
            <input type="hidden" name="cod_empresa" value="<?php echo $this->empresaId?>">

            </td>
        </tr>
      </table>
      </form>
    </div>
     


  </div>

    </div>

