<div style="padding-left: 644px;"><input type="button" name="Save" value="New" onclick="location.href='<?php  echo $this->baseUrl() ?>/estabelecimento/produto/'"></div>
<div class="dataDiv ui-corner-all" style="width: 700px;">
  <table border="0" class="gridViewTable" width="100%">
    <tr class="head">
      <td>Nome</td>
      <td>Tipo</td>
      <td>Option</td>
    </tr>
    <?php foreach ($this->paginator as $k=>$v) {?>
    <tr>
      <td><?php echo $v['nome'] ?></td>
      <td><?php echo $v['tipo'] ?></td>
      <td><a href="<?php echo $this->baseUrl() ?>/estabelecimento/produto/delete/id/<?php echo $v['cod_produto']?>" onclick="return confirm('Are you sure you want to delete?')">Delete</a>&nbsp;&nbsp;<a href="<?php echo $this->baseUrl() ?>/estabelecimento/produto/edit/id/<?php echo $v['cod_produto']?>">Edit</a></td>
    </tr>
    <?php }?>
    <tr class="head">
      <td colspan="6" align="right"><?php echo $paging ?></td>
    </tr>
  </table>
</div>

 <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
