<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />

    <link type="text/css" href="/css/portal.css" rel="stylesheet" />
    <script type="text/javascript" src="/js/jui/js/jquery-1.4.4.min.js"></script>
    <script type="text/javascript" src="/js/jui/js/jquery-ui-1.8.9.custom.min.js"></script>
    <script type="text/javascript" src="/js/portal.js"></script>
  


</head>

    <?php

	if(!empty($this->nomeCliente))
	    echo "<p>Bem vindo".  $this->nomeCliente ."! (<a href='/portal/cliente/logout'> Logout </a>) </p>";

        echo "<div style=' padding-left: 50px; clear:both; margin: 40px; color:black;' > \n";
        echo "<div style='float: left; margin: 20px 1px 20px 21px; width:200px;'><p><img src='/portal/loja/get-Logo-Empresa/id/" . $this->resultado[0]['cod_empresa'] . "' width='141' height='auto' alt=''> </p> </div> \n";
        echo "<div style='float: left; margin: 20px 1px 20px 21px; width:300px; '>  \n";
        echo  "<div style='font-weight: bold;'>" . $this->resultado[0]["razao_social"] . " </div> <br> \n";
        echo $this->resultado[0]["rua"] . " " . $this->resultado[0]["numero"]. " " . $this->resultado[0]["complemento"] . " " . $this->resultado[0]["bairro"] . " <br> \n";
        echo "Telefone 1: " . $this->resultado[0]["telefone1"] . " Telefone 2 : " . $this->resultado[0]["telefone2"] . " <br> \n";
        echo "email: " . $this->resultado[0]["email"] . " <br> \n";
	echo " </div>  \n";


    ?>


<div align="center" width="80%" style="clear:both;">

    <div style="border: solid gray; margin: 50px;">

	<?php
	if ($this->isAberto == true)
	{
	    echo "<img src='/img/open.png' align='left' />";
	}
	else if ($this->isAberto == false)
	{
	    echo "<img src=/img/close.png align='left' />";
	}
	?>

        <form action="/portal/loja/consulta" method="post" class="" id='form1'>

            <h2>Entre com os critérios de pesquisa.</h2>

            <div style="text-align: left; border: transparent; width: 380px; ">
		Ex:  macarrão, massa verde, "Macarronada da Tia Dalva"
		<br>
		Ex: catupiri, bacon, peito de peru
            </div>

	    <input type="hidden" name="cod_empresa" value="<?php echo $this->cod_empresa; ?>">
	    <input type="hidden" name="isAberto" value="<?php echo $this->isAberto; ?>">


            <br>
            <input type="textarea" name="criterio" style="width: 400px;" value="<?php echo $this->pesquisa_facapedido_criterio; ?>">
            <br>
            <br>

	    Caloria < que: <input type="text" name="caloria" style="width:50" value="<?php echo $this->pesquisa_facapedido_caloria; ?>">



	    <br><br><br>
            <input type="submit" value="Pesquisar">

        </form>
    </div>

    

    
    <!-- Imprime pedidos -->
    
 <div style="margin-right: 90px;">
        
          
                  <div style="float: right; position: relative; ">
	   
        <input type="button" value="Continuar Comprando" onclick="location.href='http://whattoeat/portal'">       
        
    </div> 

     
	      <form action="/portal/index/limpar-Carrinho" method="post" class="" >
                  <div style="float: right; position: relative; margin-right: 20px;">
		<input class="btn btn-warning" type="submit" value="Limpar Carrinho"> 
                </div>
		</form>
        
  		  <form action="/portal/pedido/fechar-Pedido" method="post" class="" >
                    <div style="float: right; margin-right: 20px; ">
                <input class="btn btn-success" type="submit" value="Fechar Pedido"> 
                </div>
		</form>

        
        <div style="clear: both;"></div>
	   
     </div>

    
     
<div style="float: right;margin-right: 90px;">
<h4> Seu pedido </h4>
        
<table  id="tableListaPedido" style=" border-spacing: 10px; border-collapse: separate;" >  
	</table>


</div>    
    


<?php
	for ($i = 0; $i < sizeof($this->resultado); $i++)
	{
?>

<div style=' clear:both; margin: 80px; color:black;'>
    <div style='float: left; margin: 20px 1px 20px 21px; width:200px;'>
	<p><img src='/portal/index/get-Imagem-Produto/id/<?php echo $this->resultado[$i]['cod_foto'] ?>' width='141' height='auto' alt=''>
	</p>
    </div>
	
    <div style='float: left; margin: 50px 1px 20px 21px; width:100px; font-size: large;'>
	<p style='display: block' >
	    <?php echo $this->resultado[$i]["nome"]; ?>
    </p> </div> <!-- nome do produto -->

        <!--	    //imprime os tamanhos disponiveis e precos do produto -->
        <div style='float: left; margin: 60px 1px 20px 80px; width:400px; font-size: medium;'>
	<?php


	    //Sempre há pelo menos um tamanho, entao imprime esse
	    if (!empty($this->resultado[$i]['preco_promocional']))
	    {
		$preco = (double) $this->resultado[$i]['preco_promocional'];
		echo ($this->resultado[$i]['tamanho'] . "=> De ");
		echo $this->resultado[$i]["preco"];
		echo (" por ");
		echo $this->resultado[$i]["preco_promocional"];
	    }
	    else
	    {
		$preco = (double) $this->resultado[$i]['preco'];
		echo $this->resultado[$i]['tamanho'] . " => " . $this->resultado[$i]["preco"];
	    }

	    //imprime o botao que vai permitir incluir no carrinho
	    if($this->isAberto)
	    {
		echo "<img style='margin-left:10px; margin-right:10px;' src='/img/incluir_mais_1.png' onclick=\"javascript:addProdutoCarrinhoAjax(".$this->cod_empresa.",".$this->resultado[$i]['cod_tamanho_produto'].",'".$this->resultado[$i]['razao_social']."','".$this->resultado[$i]['nome']."','".$this->resultado[$i]['tamanho']."',".$preco.")\"> ";
		echo "<input type='text' size='2' maxlength='2' value='1' id='quantidade_".$this->cod_empresa."_".$this->resultado[$i]['cod_tamanho_produto']."'>";
	    }
	
            if(($i+1) < sizeof($this->resultado))
            {
                $i++;
                //Esse laco verifica se existem outros tamanhos para o mesmo produto
                while (($i < sizeof($this->resultado)) && $this->resultado[$i]['cod_produto'] == $this->resultado[$i - 1]['cod_produto'])
                {
                    echo "<br> \n";

                    if (!empty($this->resultado[$i]['preco_promocional']))
                    {
                        $preco = (double) $this->resultado[$i]['preco_promocional'];
                        echo ($this->resultado[$i]['tamanho'] . "=> De ");
                        echo $this->resultado[$i]["preco"];
                        echo (" por ");
                        echo $this->resultado[$i]["preco_promocional"];
                    }
                    else
                    {
                        $preco = (double) $this->resultado[$i]['preco'];
                        echo $this->resultado[$i]['tamanho'] . " => " . $this->resultado[$i]["preco"];
                    }
                    //imprime o botao que vai permitir incluir no carrinho
                    if($this->isAberto)
                    {
                        echo "<img style='margin-left:10px; margin-right:10px;' src='/img/incluir_mais_1.png' onclick=\"javascript:addProdutoCarrinhoAjax(".$this->cod_empresa.",".$this->resultado[$i]['cod_tamanho_produto'].",'".$this->resultado[$i]['razao_social']."','".$this->resultado[$i]['nome']."','".$this->resultado[$i]['tamanho']."',".$preco.")\"> ";
                        echo "<input type='text' size='2' maxlength='2' value='1' id='quantidade_".$this->cod_empresa."_".$this->resultado[$i]['cod_tamanho_produto']."'>";

                    }

                 $i++;

                }

                $i--;
            }
	?>
    
        </div> <!-- precos -->

    <div style=' clear:both; '>
	Descrição do produto:
	<p style='font-size: smaller;' >
	    <?php echo $this->resultado[$i]["descricao"]; ?>
    </p> </div> <!-- nome do produto -->


   </div>

<?php
	}
?>

<script>

recebeCarrinhoJSON();


</script>

