<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />

	<!-- Bootstrap core CSS -->
	<link type="text/css" href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
	
	<!-- Bootstrap theme -->
	<link type="text/css" href="/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">
	
	<!-- Portal CSS-->
	<link type="text/css" href="/css/portal.css" rel="stylesheet" />
	
	<!-- jQuery -->
    <script type="text/javascript" src="/js/jui/js/jquery-1.4.4.min.js"></script>
    <script type="text/javascript" src="/js/jui/js/jquery-ui-1.8.9.custom.min.js"></script>
    <script type="text/javascript" src="/js/mootools/mootools-core-1.4.2-full-compat.js"></script>
    
    <!-- javascript Portal -->
    <script type="text/javascript" src="/js/portal.js"></script>

</head>
 <div class="header">
            <div class="logo" style="float:left;"><a href="/portal/"><img src="/img/logotipo.png"></a></div>
                <div style="float: right; margin-right: 50px; margin-top: 100px; font-size: medium;" class=""> <a href="/estabelecimento/auth" > Para seu estabelecimento </a></div>
	</div>

    <?php

        //Traz no topo as informações do estabelecimento. Nao deu pra ser igual a index do portal porque do jeito que está lá a empresa vem como resultado 
        //da busca por produto. Se não houver produto que case com a busca, também não vem empresa, e iria perder a informação que aparece no topo. 
    
	if(!empty($this->nomeCliente))
	    echo "<p>Bem vindo ".  $this->nomeCliente ."! (<a href='/portal/cliente/logout'> Logout </a>) </p>";
        
        echo "<div style=' padding-left: 50px; clear:both; margin: 40px; color:black;' > \n";
        echo "<div style='float: left; margin: 20px 1px 20px 21px; width:200px;'><p><img src='/portal/loja/get-Logo-Empresa/id/" . $this->cod_empresa."' width='141' height='auto' alt=''> </p> </div> \n";
        echo "<div style='float: left; margin: 20px 1px 20px 21px; width:300px; '>  \n";
        echo  "<div style='font-weight: bold;'>" . $this->razao_social . " </div> <br> \n";
        echo $this->rua . " " . $this->numero. " " . $this->complemento . " " . $this->bairro . " <br> \n";
        echo "Telefone 1: " . $this->telefone1 . " Telefone 2 : " . $this->telefone2 . " <br> \n";
        echo "email: " . $this->email . " <br> \n";	
        echo $this->website . " <br> \n";	echo " </div>  \n";
        

    ?>


<div align="center" width="80%" style="clear:both;">

    <div class="formBuscar">

	<?php
	if ($this->isAberto == true)
	{
	    echo "<img src='/img/open.png' align='left' />";
	}
	else if ($this->isAberto == false)
	{
	    echo "<img src=/img/close.png align='left' />";
	}
	?>

        <form action="/portal/loja/consulta" method="post" class="" id='form1'>

            <input type="hidden" name="cod_empresa" value="<?php echo $this->cod_empresa; ?>">
	    <input type="hidden" name="isAberto" value="<?php echo $this->isAberto; ?>">
            
            
            <h1>Por favor, entre com os critérios de pesquisa. Você pode procurar por ingredientes específicos, lugares, pratos ou 
            qualquer outro critério disponível para trazer a opção mais certa para você!</h1> 

            <!--<div style="text-align: left; border: transparent; width: 380px; ">
                 <p class="lead">Aqui você pode digitar qualquer termo para sua consulta:</p>
                
		Ex:  macarrão, massa verde, "Macarronada da Tia Dalva"
		<br>
		Ex: catupiri, bacon, "peito de peru", chia 
            </div>-->

            <br>
            <input class="form-control" type="textarea" name="criterio" style="width: 400px;" value="<?php echo $this->pesquisa_facapedido_criterio; ?>">
            <br>
            <br>
             <p class="lead">Culinária:</p>
            

            <div style="width:450; height: 100;">
		<?php
		//formData2 eh um array comecando do indice 0 e contendo os codigos de tipos de produtos que a empresa trabalha
		//cod_tipo_produto é um array cujo indices sao os cod_tipo_produto e o conteudo o nome do tipo. Contem todos os tipos produtos existentes.
		$i = 0;
		foreach (array_keys($this->cod_tipo_produto) as $cod_tipo_produto)
		{
		    $checked = " ";
		    if (!empty($this->pesquisa_facapedido_tipo_produto) && in_array($cod_tipo_produto, $this->pesquisa_facapedido_tipo_produto))
		    {
			$checked = "checked";
		    }
		?>
    		<input  type="checkbox" name="cod_tipo_produto[]" <?php echo $checked; ?> value="<?php echo $cod_tipo_produto ?>" class=""> <?php echo $this->cod_tipo_produto[$cod_tipo_produto] ?>

		<?php } ?>
	    </div>

            <font class="lead">Valor calórico até: </font><input  type="text" name="caloria" style="width:50" value="<?php echo $this->pesquisa_facapedido_caloria; ?>">
<br>
            <br>
            
            <p class="lead">Listar apenas estabelecimentos que oferecem: </p>
            
            
              <div style="width:450; height: 100;">
		<input  type="checkbox" name="empresa_oferece[]" <?php echo in_array('diabetico', $this->pesquisa_facapedido_empresa_oferece) ? 'checked' : '' ?> value="diabetico" class=""> Produto especial para diabético
                <input  type="checkbox" name="empresa_oferece[]" <?php echo in_array('pouco_sal', $this->pesquisa_facapedido_empresa_oferece) ? 'checked' : '' ?> value="pouco_sal" class=""> Produto com pouco sal
                <input  type="checkbox" name="empresa_oferece[]" <?php echo in_array('sem_glutem', $this->pesquisa_facapedido_empresa_oferece) ? 'checked' : '' ?> value="sem_glutem" class=""> Produto sem glútem
                <input  type="checkbox" name="empresa_oferece[]" <?php echo in_array('lactose', $this->pesquisa_facapedido_empresa_oferece) ? 'checked' : '' ?> value="lactose" class=""> Produto sem lactose
		<input  type="checkbox" name="empresa_oferece[]" <?php echo in_array('organico', $this->pesquisa_facapedido_empresa_oferece) ? 'checked' : '' ?> value="organico" class=""> Produto orgânico	
              </div>

	    <br><br><br>
            <input class="btn btn-primary" type="submit" value="Pesquisar">


        </form>
    </div>

    

    
    <!-- Imprime pedidos -->
    
 <div style="margin-right: 90px;">
        
          
                  <div style="float: right; position: relative; ">
	   
        <input class="btn btn-warning" type="button" value="Continuar Comprando" onclick="location.href='/portal/index'">       
        
    </div> 

     
	      <form action="/portal/index/limpar-Carrinho" method="post" class="" >
                  <div style="float: right; position: relative; margin-right: 20px;">
		<input class="btn btn-warning" type="submit" value="Limpar Carrinho"> 
                </div>
		</form>
        
  		  <form action="/portal/pedido/fechar-Pedido" method="post" class="" >
                    <div style="float: right; margin-right: 20px; ">
                <input class="btn btn-success" type="submit" value="Fechar Pedido"> 
                </div>
		</form>

        
        <div style="clear: both;"></div>
	   
     </div>

    
     
<div style="float: right;margin-right: 90px;">
<h4> Seu pedido </h4>
        
<table  id="tableListaPedido" style=" border-spacing: 10px; border-collapse: separate;" >  
	</table>


</div>    
    


<?php
	for ($i = 0; $i < sizeof($this->resultado); $i++)
	{
?>

    
<div style=' clear:both;  color:black;'>
    <div style='float: left; margin: 20px 1px 20px 20px; '>
	<p><img src='/portal/index/get-Imagem-Produto/id/<?php echo $this->resultado[$i]['cod_foto'] ?>' width='100' height='auto' alt=''>
	</p>
    </div>
	
    <div style='float: left; margin: 30px 1px 10px 10px; width:400px; font-size: medium;'>
	<p style='display: block' >
	    <?php echo $this->resultado[$i]["nome"]; ?>
            <p style='font-size: small;'> 
	    <?php echo $this->resultado[$i]["descricao"]."<br> Valor calórico: ".$this->resultado[$i]["valor_calorico"]." cal"; ?>
    </p>
    </p> </div> <!-- nome do produto -->

        <!--	    //imprime os tamanhos disponiveis e precos do produto -->
        <div style='float: left; margin: 35px 1px 10px 10px; font-size: medium; text-align: left'>
	<?php


	    //Sempre há pelo menos um tamanho, entao imprime esse
	    if (!empty($this->resultado[$i]['preco_promocional']))
	    {
		$preco = (double) $this->resultado[$i]['preco_promocional'];
		echo ($this->resultado[$i]['tamanho'] . "De ");
		echo $this->resultado[$i]["preco"];
		echo (" por ");
		echo $this->resultado[$i]["preco_promocional"];
	    }
	    else
	    {
		$preco = (double) $this->resultado[$i]['preco'];
		echo $this->resultado[$i]['tamanho'] . "  " . $this->resultado[$i]["preco"];
	    }

	    //imprime o botao que vai permitir incluir no carrinho
	    if($this->isAberto)
	    {
	        echo "<img src='/img/Create.png' style='margin-left:5px;'  onclick=\"javascript:addProdutoCarrinhoAjax(".$this->resultado[$i]['cod_empresa'].",".$this->resultado[$i]['cod_tamanho_produto'].",'".$this->resultado[$i]['razao_social']."','".$this->resultado[$i]['nome']."','".$this->resultado[$i]['tamanho']."',".$preco.")\"> ";
          	echo "<input type='text' style='visibility: hidden;' size='2' maxlength='2' value='1' id='quantidade_".$this->resultado[$i]['cod_empresa']."_".$this->resultado[$i]['cod_tamanho_produto']."'>";
	    }
            
	
            if(($i+1) < sizeof($this->resultado))
            {
                $i++;
                //Esse laco verifica se existem outros tamanhos para o mesmo produto
                while (($i < sizeof($this->resultado)) && $this->resultado[$i]['cod_produto'] == $this->resultado[$i - 1]['cod_produto'])
                {
                    echo "<br> \n";

                    if (!empty($this->resultado[$i]['preco_promocional']))
                    {
                        $preco = (double) $this->resultado[$i]['preco_promocional'];
                        echo ($this->resultado[$i]['tamanho'] . " De ");
                        echo $this->resultado[$i]["preco"];
                        echo (" por ");
                        echo $this->resultado[$i]["preco_promocional"];
                    }
                    else
                    {
                        $preco = (double) $this->resultado[$i]['preco'];
                        echo $this->resultado[$i]['tamanho'] . "  " . $this->resultado[$i]["preco"];
                    }
                    //imprime o botao que vai permitir incluir no carrinho
                    if($this->isAberto)
                    {
                         echo "<img src='/img/Create.png' style='margin-left:5px;'  onclick=\"javascript:addProdutoCarrinhoAjax(".$this->resultado[$i]['cod_empresa'].",".$this->resultado[$i]['cod_tamanho_produto'].",'".$this->resultado[$i]['razao_social']."','".$this->resultado[$i]['nome']."','".$this->resultado[$i]['tamanho']."',".$preco.")\"> ";
                         echo "<input type='text' style='visibility: hidden;' size='2' maxlength='2' value='1' id='quantidade_".$this->resultado[$i]['cod_empresa']."_".$this->resultado[$i]['cod_tamanho_produto']."'>";

                    }

                 $i++;

                }

                $i--;
            }
	?>
    
        </div> <!-- precos -->
    
    
    
  </div>
    

<?php
	}
?>

<script>

recebeCarrinhoJSON();


</script>

