<div style="padding-left: 644px;"><input type="button" name="Save" value="New" onclick="location.href='<?php  echo $this->baseUrl() ?>/estabelecimento/produto/'"></div>
<div class="dataDiv ui-corner-all" style="width: 700px;">
  <table border="0" class="gridViewTable" width="100%">
    <tr class="head">
      <td>Nome</td>
      <td>Tipo</td>
      <td>Option</td>
    </tr>
    <?php foreach ($this->paginator as $k=>$v) {?>
    <tr>
      <td><?php echo $v['nome'] ?></td>
      <td><?php echo $v['tipo'] ?></td>
      <td>
          
           <form action="" method="post" id="gridForm"> 
              <input type="hidden" value="" name="produtoId" id="cod_produto">
              <!--    <a href="<?php //echo $this->baseUrl() ?>/estabelecimento/produto/delete/id/<?php //echo $v['cod_produto']?>" onclick="return confirm('Are you sure you want to delete?')">Delete</a>-->

              <a href="#" onclick="javascript:removeGrid(<?php echo $v['cod_produto']?>)">Excluir</a>
              &nbsp;&nbsp;
              <!--<a href="<?php// echo $this->baseUrl() ?>/estabelecimento/produto/edit/id/<?php// echo $v['cod_produto']?>">Edit</a> -->
              <a href="#" onclick="javascript:editaGrid(<?php echo $v['cod_produto']?>)">Editar</a>
          </form>



      </td>
    </tr>
    <?php }?>
    <tr class="head">
      <td colspan="6" align="right"><?php echo $this->paging ?></td>
    </tr>
  </table>
</div>


 <script type="text/javascript">

    function removeGrid(valor){

        if (confirm('Tem certeza que deseja remover o registro?'))
        {
         var url='/estabelecimento/produto/delete';
         document.getElementById('gridForm').action = url;
         document.getElementById('cod_produto').value = valor;
         document.getElementById('gridForm').submit();
        }

    }

  function editaGrid(valor){

         var url='/estabelecimento/produto/edit';
         document.getElementById('gridForm').action = url;
         document.getElementById('cod_produto').value = valor;
         document.getElementById('gridForm').submit();


    }



    </script>



 <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
