<div style="padding-left: 644px;"><input type="button" name="Save" value="New" onclick="location.href='<?php  echo $this->baseUrl() ?>/estabelecimento/funcionario/'"></div>
<div class="dataDiv ui-corner-all" style="width: 700px;">
  <table border="0" class="gridViewTable" width="100%">
  <tr><td colspan="10"></td></tr>
    <tr class="head">
      <td>Nome </td>
      <td>Empresa</td>
      <td>Date</td>
      <td>Option</td>
    </tr>
    <?php foreach ($this->paginator as $k=>$v) {?>
    <tr>
      <td><?php echo $v['nome'] ?></td>
      <td><?php echo $v['empresa'] ?></td>
      <td><?php echo date('d-m-Y',strtotime($v['data_cadastro'])); ?></td>
      <td><a href="<?php echo $this->baseUrl() ?>/estabelecimento/funcionario/delete/id/<?php echo $v['cod_funcionario']?>" onclick="return confirm('Are you sure you want to delete?')">Delete</a>&nbsp;&nbsp;<a href="<?php echo $this->baseUrl() ?>/estabelecimento/funcionario/edit/id/<?php echo $v['cod_funcionario']?>">Edit</a></td>
    </tr>
    <?php }?>
    <tr class="head">
      <td colspan="6" align="right"><?php echo $paging ?></td>
    </tr>
  </table>
</div>

 <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
