<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
    <h2> Parabéns, sua compra foi realizada com sucesso. </h2>

    Você pode acompanhar detalhes do seu pedido clicando nesse <a href="#" > link. </a>
  </body>
</html>
