<?php echo $this->doctype(); ?>
<html>
	<head>		
		<?php echo $this->headMeta();?>
		<?php echo $this->headTitle();?>
		<?php echo $this->headLink();?>
		<?php echo $this->JQuery()->enable();?>
		<?php echo $this->headScript();?>
	</head>	
<body>
<div id="tudo">

	<div id="topo">
		
		<div class="container-topo">
			<div id="titulos">
				<img src="<?php echo $this->baseUrl("/img/subway.jpg")?>" >
				<h1>Bem-vindo(a), <i>Christian Pior</i> - <small><a href="/estabelecimento/auth/logout">(sair)</a></small></h1>
			</div>
			<div id="infos">
				<img id="faturamento" src="<?php echo $this->baseUrl("/img/Coins.png")?>">
				<span>Faturamento de Hoje: <b>R$ 6,66</b></span><br />
				<span><a href="#">Histórico de faturamentos</a></span>
				<b class="botao">Agendar Recebimento</b>
			</div>
		</div>
		
		<div class="container-topo last">
			<ul id="carrossel" class="jcarousel-skin-tango">
				 <li>
				 	<img src="<?php echo $this->baseUrl("/img/Tool.png")?>"><h4>Configurações</h4>
				 </li> 
				<li id="menu_pedido">
					<img src="<?php echo $this->baseUrl("/img/Block.png")?>" ><h4>Pedidos</h4>
				</li>
				<li id="menu_usuario">
					<img src="<?php echo $this->baseUrl("/img/community-users-icon.png")?>"><h4>Usuários</h4>
				</li>
				<li>
					<img src="<?php echo $this->baseUrl("/img/checkout.png")?>"><h4>Saldos</h4>
				</li>
				<li>
					<img src="<?php echo $this->baseUrl("/img/Pencil and ruler-64.png")?>"></img><h4>Editar</h4>
				</li>
				<li>
					<img src="<?php echo $this->baseUrl("/img/megaphone.png")?>"></img><h4>Publicidade</h4>
				</li>
				<li>
					<img src="<?php echo $this->baseUrl("/img/Talk-64.png")?>"></img><h4>Suporte</h4>
				</li>
				<li>
					<img src="<?php echo $this->baseUrl("/img/04_maps_64.png")?>"><h4>Regiões/entregas</h4>
				</li>
				<li>
					<img src="<?php echo $this->baseUrl("/img/credit-cards.png")?>"><h4>Pagamentos</h4>
				</li>
				<li>
					<img src="<?php echo $this->baseUrl("/img/delivery.png")?>"><h4>Entregas</h4>
				</li> 
			</ul>	
		</div>
		
		<div id="submenu">
						<ul id="submenu_pedido">
							<li><a href="cpainel/monitoramento.phtml">Monitorar pedidos</a></li>
							<li><a href="">Historico de pedidos</a></li>
						</ul>
						<ul id="submenu_usuario">
							<li><a href="">Cadastrar usuário</a></li>
							<li><a href="">Gerenciar usuários</a></li>
						</ul>
		</div>

	</div>
	
	
	<div id="container-principal">
			
		<?php echo $this->layout()->content;?>
		
	</div>


	<div id="footer">
		<ul>
			<li><a>Rodapé</a></li>
			<li><a>Atendimento online</a></li>
			<li><a>Tutoriais</a></li>
			<li><a>Rodapé</a></li>
			<li><a>Atendimento online</a></li>
			<li><a>Tutoriais</a></li>
			<li><a>Rodapé</a></li>
			<li><a>Atendimento online</a></li>
			<li><a>Tutoriais</a></li>		
		</ul>
	</div>
	
</div>	
</body>
</html>	