<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />

<?php //echo $this->headMeta(); ?>

<title><?php echo $this->pageTitle;?></title>

<link type="text/css" href="/js/jui/css/pepper-grinder/jquery-ui-1.8.9.custom.css" rel="stylesheet" />
<script type="text/javascript" src="/js/jui/js/jquery-1.4.4.min.js"></script>
<script type="text/javascript" src="/js/jui/js/jquery-ui-1.8.9.custom.min.js"></script>
<script type="text/javascript" src="/js/validation-new.js"></script>
<script type="text/javascript" src="/js/common.js"></script>
<script type="text/javascript" src="/js/jquery.cookie.js"></script>

</head>

<body>

<?php echo $this->layout()->content; ?>
</body>
</html>
