<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />

	<!-- Bootstrap core CSS -->
	<link type="text/css" href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
	
	<!-- Bootstrap theme -->
	<link type="text/css" href="/bootstrap/bootstrap-theme.min.css" rel="stylesheet">
	
	<!-- Portal CSS-->
	<link type="text/css" href="/css/portal.css" rel="stylesheet" />
	
	<!-- jQuery -->
    <script type="text/javascript" src="/js/jui/js/jquery-1.4.4.min.js"></script>
    <script type="text/javascript" src="/js/jui/js/jquery-ui-1.8.9.custom.min.js"></script>
    
    <!-- javascript Portal -->
    <script type="text/javascript" src="/js/portal.js"></script>

</head>

	<div class="topo">
		<div class="logo" style="float:left;"><img src="/img/logotipo.png"></div>
                <div style="float: right;" class=""> <a href="/estabelecimento/auth" > Para seu estabelecimento </a></div>
	</div>
    <?php

	if(!empty($this->nomeCliente))
	     echo "<p>Bem vindo".  $this->nomeCliente ."! (<a href='/portal/cliente/logout'> Logout </a>) </p>";


    ?>

<div align="center" width="80%">

    <div class="formBuscar">
        <form action="/portal/index/consulta" method="post" class="" id='form1'>

            <h1>Entre com os critérios de pesquisa por favor. Você pode procurar por ingredientes específicos, lugares, pratos ou 
            qualquer outro critério disponível para te trazer a opção mais certa para você!</h1> 

            <div style="text-align: left; border: transparent; width: 380px; ">
                 <p class="lead">Aqui você pode digitar qualquer termo para sua consulta:</p>
                
		Ex:  macarrão, massa verde, "Macarronada da Tia Dalva"
		<br>
		Ex: catupiri, bacon, "peito de peru", chia 
            </div>

            <br>
            <input class="form-control" type="textarea" name="criterio" style="width: 400px;" value="<?php echo $this->pesquisa_facapedido_criterio; ?>">
            <br>
            <br>
             <p class="lead">Culinária:</p>
            

            <div style="width:450; height: 100;">
		<?php
		//formData2 eh um array comecando do indice 0 e contendo os codigos de tipos de produtos que a empresa trabalha
		//cod_tipo_produto é um array cujo indices sao os cod_tipo_produto e o conteudo o nome do tipo. Contem todos os tipos produtos existentes.
		$i = 0;
		foreach (array_keys($this->cod_tipo_produto) as $cod_tipo_produto)
		{
		    $checked = " ";
		    if (!empty($this->pesquisa_facapedido_tipo_produto) && in_array($cod_tipo_produto, $this->pesquisa_facapedido_tipo_produto))
		    {
			$checked = "checked";
		    }
		?>
    		<input  type="checkbox" name="cod_tipo_produto[]" <?php echo $checked; ?> value="<?php echo $cod_tipo_produto ?>" class=""> <?php echo $this->cod_tipo_produto[$cod_tipo_produto] ?>

		<?php } ?>
	    </div>

            <p class="lead">Valor calórico até: </p><input class="form-control" type="text" name="caloria" style="width:50" value="<?php echo $this->pesquisa_facapedido_caloria; ?>">
<br>
            <br>
            
            <p class="lead">Listar apenas estabelecimentos que oferecem: </p>
            
            
              <div style="width:450; height: 100;">
		<input  type="checkbox" name="empresa_oferece[]" <?php echo in_array('diabetico', $this->pesquisa_facapedido_empresa_oferece) ? 'checked' : '' ?> value="diabetico" class=""> Produto especial para diabético
                <input  type="checkbox" name="empresa_oferece[]" <?php echo in_array('pouco_sal', $this->pesquisa_facapedido_empresa_oferece) ? 'checked' : '' ?> value="pouco_sal" class=""> Produto com pouco sal
                <input  type="checkbox" name="empresa_oferece[]" <?php echo in_array('sem_glutem', $this->pesquisa_facapedido_empresa_oferece) ? 'checked' : '' ?> value="sem_glutem" class=""> Produto sem glútem
                <input  type="checkbox" name="empresa_oferece[]" <?php echo in_array('lactose', $this->pesquisa_facapedido_empresa_oferece) ? 'checked' : '' ?> value="lactose" class=""> Produto sem lactose
		<input  type="checkbox" name="empresa_oferece[]" <?php echo in_array('organico', $this->pesquisa_facapedido_empresa_oferece) ? 'checked' : '' ?> value="organico" class=""> Produto orgânico	
              </div>

	    <br><br><br>
            <input class="btn btn-primary" type="submit" value="Pesquisar">

        </form>
    </div>

<h3>Nosso sistema ainda não faz pedidos mas você pode simular suas compras e verificar o custo total. Compre em quantos estabelecimentos quiser. 
    Todos os itens escolhidos ficarão no seu carrinho.</h3>
    
    <div style="margin-right: 90px;">
        
	      <form action="/portal/index/limpar-Carrinho" method="post" class="" >
                  <div style="float: right; position: relative; ">
		<input class="btn btn-warning" type="submit" value="Limpar Carrinho"> 
                </div>
		</form>
        
  		  <form action="/portal/pedido/fechar-Pedido" method="post" class="" >
                    <div style="float: right; margin-right: 20px; ">
                <input class="btn btn-success" type="submit" value="Fechar Pedido"> 
                </div>
		</form>

        
        <div style="clear: both;"></div>
	   
     </div>

    
     
<div style="float: right;margin-right: 90px;">
<h4> Seu pedido </h4>
        
<table  id="tableListaPedido" style=" border-spacing: 10px; border-collapse: separate;" >  
	</table>


</div>


<p style="padding-left: 50px;"><?php $this->headline; ?></p>



<?php
		for ($i = 0; $i < sizeof($this->resultado); $i++)
		{
		    echo "<div style=' clear:both; margin: 80px; color:black;' > \n";

		    echo "<div style='float: left; margin: 20px 1px 20px 21px; width:200px;'><p><img src='/portal/loja/get-Logo-Empresa/id/" . $this->resultado[$i]['cod_empresa'] . "' width='141' height='auto' alt=''> </p> </div> \n";
		    echo "<div style='float: left; margin: 20px 1px 20px 21px; width:300px; '>  \n";
		    echo  "<div style='font-weight: bold;'>" . $this->resultado[$i]["razao_social"] . " </div> <br> \n";
                    echo $this->resultado[$i]["rua"] . " " . $this->resultado[$i]["numero"]. " " . $this->resultado[$i]["complemento"] . " " . $this->resultado[$i]["bairro"] . " <br> \n";
                    echo "Telefone 1: " . $this->resultado[$i]["telefone1"] . " Telefone 2 : " . $this->resultado[$i]["telefone2"] . " <br> \n";
                    echo "email: " . $this->resultado[$i]["email"] . " <br> \n";
                    echo  $this->resultado[$i]["website"] . " <br> \n";
		    echo " </div> \n";


		    //verifica se a empresa esta atendendo nesse horario
		    if ($this->resultado[$i]['isAberto'] == true)
		    {
			echo "<div style='float: left; margin: 60px 1px 20px 21px; width:150px;'> \n";
			echo "<a class='botao_portal_vermelho' target='' title='Ir &agrave; Loja' href='javascript:irLoja(\"" . $this->resultado[$i]['url'] . "\")'>" .
			"<span>Ir &agrave; Loja</span></a> </div>";
		    }
		    else
		    {
			$hora_atual = date('H') . ":" . date('i') . ":00";
			echo "<div style='float: left; margin: 60px 1px 20px 21px; width:150px;'> \n";
			echo "<a class='botao_portal_amarelo' target=''	title='Fechada nesse horário' href='#' onclick='lojaFechada(".$this->resultado[$i]['cod_empresa'].",".$this->resultado[$i]['cod_produto'].",".$i. ")'".
			" <span>Fechada nesse horário </span> </a> <span class='msg_estabelecimento_fechado' id='spanFechada".$i."'>Clique no botão se deseja enviar à loja sua vontade ".
			" de que ela estivesse aberta. </span> </div>";
		    }
  
		    echo "</div> \n";
		}
?>


<script>

recebeCarrinhoJSON();

function irLoja(url)
{
    var form = document.getElementById("form1");
    form.action = "/"+url;
    form.submit();

}


</script>
