<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <link rel="shortcut icon" type="image/ico" href="img/favicon.ico"/>
    <!-- Bootstrap core CSS -->
    <link type="text/css" href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Bootstrap theme -->
    <link type="text/css" href="/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Portal CSS-->
    <link type="text/css" href="/css/portal.css" rel="stylesheet" />
 <link type="text/css" href="/css/style.css" rel="stylesheet">

    <script type="text/javascript" src="/js/jui/js/jquery-1.4.4.min.js"></script>
    <script type="text/javascript" src="/js/jui/js/jquery-ui-1.8.9.custom.min.js"></script>
    <script type="text/javascript" src="/js/mootools/mootools-core-1.4.2-full-compat.js"></script>
    <script src="<?php echo $this->serverUrl(); ?>/js/jquery.min.js"></script>
    <!-- javascript Portal -->
    <script type="text/javascript" src="/js/portal.js"></script>

        <script type="text/javascript">
        $(document).ready(function () {
           
            $('#pesquisaInicio').focus();
            $('.filterexpand').click(function () {
              /*  $('#front_filtro_menu').animate({
                    height: 'toggle'
                }); //Mostra MEnu Filtro */   
        //      $(".chkclass").toggle();
                $("#front_filtro_menu").slideToggle(1000);
                $('#confirmaFiltro').click(function () {
                    //$('#front_filtro_menu').fadeOut()
                    $('#front_filtro_menu').fadeOut()
                });

            });
            $('#botaoAddCarrinho').click(function () {
                $('#RemoveAdd').fadeIn()
            })


        });// fim document

    </script>
    <style>
    .filterexpand {
  color: rgb(0, 0, 0) !important;
  float: left;
  padding: 2px 0px;
  text-align: left;
  width: auto;
  cursor:pointer;
}



#filtroMenu {
  background: none repeat scroll 0 0 rgb(238, 238, 238);
  border: medium none rgb(204, 204, 204);
  border-radius: 0;
  color: rgb(102, 102, 102);
  display: none;
  font-family: arial !important;
  font-size: 19px;
  height: auto;
  margin-top: 0;
  padding: 30px 68px;
  text-align: left;
  top: 215px;
  width: 682px;
}
#filtroMenu div{
    font-size:14px;
}
        #confirmaFiltro{
            margin-top:15px;
        }
        #filtroResult:hover{cursor: pointer;opacity: 0.8}
        #filtroResult{position:absolute;margin-top:-68px;margin-left:550px;background: rgba(0,0,0,0.7);padding: 10px;border: none;color: #FFFFFF;font-weight: bold;font-size: 20px}
        #filtroMenu input{margin-left: 0px}
.mainouter {
  background-color: rgb(238, 238, 238);
  color: rgb(0, 0, 0);
  float: left;
  margin-bottom: 10px;
  padding: 25px;
  width: 100% !important;
}
      .innerimg {
  float: left;
  margin: 0;
}
        .inner_filter{
            position:relative;
            margin-top:60px;
        }

        .inner_filter #filtroResult {
            position: absolute;
            top: -48px;
            right: 315px;
            background: rgba(0,0,0,0.7);
            padding: 10px;
            border: none;
            color: #FFFFFF;
            font-weight: bold;
            font-size: 20px;
            /* left: 0; */
            margin: auto;}
        .formBuscar {
            background: none repeat scroll 0 0 rgb(254, 254, 254);
            margin: 0;
            padding: 14px;
        }

        .inner_searchbar {
            background: #eee;
            box-shadow: none;
                margin-top: 0px;
            padding: 25px;
            position: relative;
            width: 682px;}
        .serchbutn{
            background: none repeat scroll 0 0 rgb(255, 0, 51);
            border: medium none;
            color: rgb(255, 255, 255);
            font-family: arial;
            font-size: 18px;
            font-weight: bold;
            padding: 17px;
            border-radius:0px;
        }
  .inputbtn {
  background: none repeat scroll 0 0 rgb(255, 255, 255);
  border: 1px solid rgb(204, 204, 204);
  border-radius: 0;
  box-shadow: none;
  float: left;
  height: 60px;
  padding: 20px;
  width: 510px;
}
.inner_cart {
  border: 1px solid rgb(221, 221, 221);
  float: right;
  margin-right: 0;
  margin-top: 18px;
  padding: 0 15px;
  margin-bottom: 50px;
}
.innerimg p{
    margin-bottom:0px;
}



.inner_filter {
    position: relative;
    margin-top: 0;}
        /*.formBuscar h1{
            font-size: 24px;
            line-height: 32px;}*/
        
        
        #botaoEstabelecimento {
          position: absolute;
          right: 0;
          top: 0;
         }
        #botaoEstabelecimento:hover{cursor: pointer;opacity: 0.8}
        #confirmaFiltro{background: #00CC66;border: none;padding: 5px;color: #FFFFFF;float: right;border-radius: 3px;}

        #filtroMenu{display:none;font-family:arial !important;background: #FFFFFF;padding: 10px;border-radius: 3px;border:#CCCCCC;font-size: 19px;
                    position:absolute;top: 215px;color: #666666;height: auto;}
#EnglobaPesquisaInicio {
  background: none repeat scroll 0 0 rgba(255, 255, 255, 0.7);
  box-shadow: 0 2px 2px 0 rgb(0, 0, 0);
  margin-top: 160px;
  padding: 25px;
  position: relative;
  width: 550px;
}
        #pesquisaInicio{padding:20px;width: 550px;background:#FFFFFF;border: none;}
        ::-webkit-input-placeholder {color: #666666;font-size: 16px;vertical-align: middle;}

        :-moz-placeholder { /* Firefox 18- */color: #666666;  font-size: 16px;vertical-align: middle;}

        ::-moz-placeholder {  /* Firefox 19+ */  color: #666666;font-size: 16px;vertical-align: middle;}

        :-ms-input-placeholder {  color: #666666; font-size:16px;vertical-align: middle;}
        #botaoPesquisar:hover{cursor: pointer;opacity: 0.8}
        #botaoPesquisar{font-family:arial;background: #FF0033;padding: 17px;color: #FFFFFF;border: none;font-weight: bold;
                        font-size: 18px}
        #borderTopo{width: 100%;height: 5px;background: #FFBF00;position: absolute;top: 0px;left: 0px;}
        #logoComabem img{float:left;clear: both;width: 214px;height: 85px}
        #filtroResult:hover{cursor: pointer;opacity: 0.8}
        #filtroResult{position:absolute;margin-top:-68px;margin-left:550px;background: rgba(0,0,0,0.7);padding: 10px;border: none;color: #FFFFFF;font-weight: bold;font-size: 20px}
        #filtroMenu input{margin-left: 0px}
        
    </style>

</head>
<div class="header">
    <div class="logo" style="float:left;"><a href="/portal/"><img src="/img/logotipo.png"></a></div>
    <div class="store_Address" style="float: right; margin-right: 50px; margin-top: 100px; font-size: medium;" class=""> <a href="/estabelecimento/auth" > Para seu estabelecimento </a></div>
</div>

<?php
//Traz no topo as informações do estabelecimento. Nao deu pra ser igual a index do portal porque do jeito que está lá a empresa vem como resultado 
//da busca por produto. Se não houver produto que case com a busca, também não vem empresa, e iria perder a informação que aparece no topo. 

if (!empty($this->nomeCliente))
    echo "<p>Bem vindo " . $this->nomeCliente . "! (<a href='/portal/cliente/logout'> Logout </a>) </p>";

echo "<div class='nomeCliente' style=' padding-left: 0px; clear:both; margin: 40px; color:black;' > \n";
echo "<div class='nomeCliente2' style='float: left; margin: 20px 1px 20px 0px; width:auto;'><p><img src='/portal/loja/get-Logo-Empresa/id/" . $this->cod_empresa . "' width='141' height='auto' alt=''> </p> </div> \n";
echo "<div class='firstimgtext'>  \n";
echo "<div style='font-weight: bold;'>" . $this->razao_social . " </div> <br> \n";
echo $this->rua . " " . $this->numero . " " . $this->complemento . " " . $this->bairro . " <br> \n";
echo "Telefone 1: " . $this->telefone1 . " Telefone 2 : " . $this->telefone2 . " <br> \n";
echo "email: " . $this->email . " <br> \n";
echo $this->website . " <br> \n";
echo " </div>  \n";
?>






<div align="center" width="80%" style="clear:both;">

    <div class="inner_search"> 

        <?php
        if ($this->isAberto == true) {
            echo "<img src='/img/open.png' align='left' />";
        } else if ($this->isAberto == false) {
            echo "<img src=/img/close.png align='left' />";
        }
        ?>

        <form action="/portal/loja/consulta" method="post" class="" id='form1'>

            <input type="hidden" name="cod_empresa" value="<?php echo $this->cod_empresa; ?>">
            <input type="hidden" name="isAberto" value="<?php echo $this->isAberto; ?>">


            <br>
            <div id="EnglobaPesquisaInicio">
 
            
                
  
                              <input class="form-control" type="textarea" name="criterio" id="pesquisaInicio"  
                       value="" placeholder="Ingredientes específicos, lugares, pratos..."><input class="btn btn-primary" id="botaoPesquisar" type="submit" 
                       value="BUSCAR">
              <span class="filterexpand"> Mais opcoes de filtro</span>
                </div>
<br>
<br>
            
            
            <div id="front_filtro_menu" class="expanddv">
                            <div  class="margbtm">
           
                <?php
//formData2 eh um array comecando do indice 0 e contendo os codigos de tipos de produtos que a empresa trabalha
//cod_tipo_produto é um array cujo indices sao os cod_tipo_produto e o conteudo o nome do tipo. Contem todos os tipos produtos existentes.
                $i = 0;
                foreach (array_keys($this->cod_tipo_produto) as $cod_tipo_produto) {
                    $checked = " ";
                    if (!empty($this->pesquisa_facapedido_tipo_produto) && in_array($cod_tipo_produto, $this->pesquisa_facapedido_tipo_produto)) {
                        $checked = "checked";
                    }
                    ?>
                    <input  type="checkbox" name="cod_tipo_produto[]" <?php echo $checked; ?> value="<?php echo $cod_tipo_produto ?>" class=""> <?php echo $this->cod_tipo_produto[$cod_tipo_produto] ?>

                <?php } ?>
            </div>
                
                
                
                  <!--p class="lead">Culinária:</p-->
                <font class="lead">Valor calórico até: </font><input  type="text" name="caloria" style="width:50" value="<?php echo $this->pesquisa_facapedido_caloria; ?>">
                <br>
                <br>

                <p class="lead">Listar apenas estabelecimentos que oferecem: </p>



                <input  type="checkbox" name="empresa_oferece[]" <?php echo in_array('diabetico', $this->pesquisa_facapedido_empresa_oferece) ? 'checked' : '' ?> value="diabetico" class=""> Produto especial para diabético<br>
                <input  type="checkbox" name="empresa_oferece[]" <?php echo in_array('pouco_sal', $this->pesquisa_facapedido_empresa_oferece) ? 'checked' : '' ?> value="pouco_sal" class=""> Produto com pouco sal<br>
                <input  type="checkbox" name="empresa_oferece[]" <?php echo in_array('sem_glutem', $this->pesquisa_facapedido_empresa_oferece) ? 'checked' : '' ?> value="sem_glutem" class=""> Produto sem glútem<br>
                <input  type="checkbox" name="empresa_oferece[]" <?php echo in_array('lactose', $this->pesquisa_facapedido_empresa_oferece) ? 'checked' : '' ?> value="lactose" class=""> Produto sem lactose<br>
                <input  type="checkbox" name="empresa_oferece[]" <?php echo in_array('organico', $this->pesquisa_facapedido_empresa_oferece) ? 'checked' : '' ?> value="organico" class=""> Produto orgânico<br>
                <input type="button" id="confirmaFiltro" value="&#10004; Ok">	
            </div>

            <br><br><br>
<!--            <input class="btn btn-primary" type="submit" value="Pesquisar">-->


        </form>
    </div>




    <!-- Imprime pedidos -->

    <div class="topdiv">


        <div class="topdiv_btn1">

            <input class="btn btn-warning" type="button" value="Continuar Comprando" onclick="location.href = '/portal/index'">       

        </div> 


        <form action="/portal/index/limpar-Carrinho" method="post" class="" >
            <div class="topdiv_btn2">
                <input class="btn btn-warning" type="submit" value="Limpar Carrinho"> 
            </div>
        </form>

        <form action="/portal/pedido/fechar-Pedido" method="post" class="" >
            <div class="topdiv_btn3">
                <input class="btn btn-success" type="submit" value="Fechar Pedido"> 
            </div>
        </form>


        <div style="clear: both;"></div>

    </div>



    <div class="inner_cart">
        <h4> Seu pedido </h4>

        <table  id="tableListaPedido" style=" border-spacing: 10px; border-collapse: separate;" >  
        </table>


    </div>    



    <?php
    for ($i = 0; $i < sizeof($this->resultado); $i++) {
        ?>


        <div class="mainouter" >
            <div class="innerimg">
                <p><img src='/portal/index/get-Imagem-Produto/id/<?php echo $this->resultado[$i]['cod_foto'] ?>' width='100' height='auto' alt=''>
                </p>
            </div>

            <div class="imgtext">
                <p style='display: block' >
                    <?php echo $this->resultado[$i]["nome"]; ?>
                <p style='font-size: small;'> 
                    <?php echo $this->resultado[$i]["descricao"] . "<br> Valor calórico: " . $this->resultado[$i]["valor_calorico"] . " cal"; ?>
                </p>
                </p> </div> <!-- nome do produto -->

            <!--	    //imprime os tamanhos disponiveis e precos do produto -->
            <div class="rytsec">
                <?php
                //Sempre há pelo menos um tamanho, entao imprime esse
                if (!empty($this->resultado[$i]['preco_promocional'])) {
                    $preco = (double) $this->resultado[$i]['preco_promocional'];
                    echo ($this->resultado[$i]['tamanho'] . "De ");
                    echo $this->resultado[$i]["preco"];
                    echo (" por ");
                    echo $this->resultado[$i]["preco_promocional"];
                } else {
                    $preco = (double) $this->resultado[$i]['preco'];
                    echo $this->resultado[$i]['tamanho'] . "  " . $this->resultado[$i]["preco"];
                }

                //imprime o botao que vai permitir incluir no carrinho
               if ($this->isAberto) {
                    echo "<img src='/img/Create.png' style='margin-left:5px;'  onclick=\"javascript:addProdutoCarrinhoAjax(" . $this->resultado[$i]['cod_empresa'] . "," . $this->resultado[$i]['cod_tamanho_produto'] . ",'" . $this->resultado[$i]['razao_social'] . "','" . $this->resultado[$i]['nome'] . "','" . $this->resultado[$i]['tamanho'] . "'," . $preco . ")\"> ";
                    echo "<input type='text' style='visibility: hidden;' size='2' maxlength='2' value='1' id='quantidade_" . $this->resultado[$i]['cod_empresa'] . "_" . $this->resultado[$i]['cod_tamanho_produto'] . "'>";
                }


                if (($i + 1) < sizeof($this->resultado)) {
                    $i++;
                    //Esse laco verifica se existem outros tamanhos para o mesmo produto
                    while (($i < sizeof($this->resultado)) && $this->resultado[$i]['cod_produto'] == $this->resultado[$i - 1]['cod_produto']) {
                        echo "<br> \n";

                        if (!empty($this->resultado[$i]['preco_promocional'])) {
                            $preco = (double) $this->resultado[$i]['preco_promocional'];
                            echo ($this->resultado[$i]['tamanho'] . " De ");
                            echo $this->resultado[$i]["preco"];
                            echo (" por ");
                            echo $this->resultado[$i]["preco_promocional"];
                        } else {
                            $preco = (double) $this->resultado[$i]['preco'];
                            echo $this->resultado[$i]['tamanho'] . "  " . $this->resultado[$i]["preco"];
                        }
                        //imprime o botao que vai permitir incluir no carrinho
                       if ($this->isAberto) {
                            echo "<img src='/img/Create.png' style='margin-left:5px;'  onclick=\"javascript:addProdutoCarrinhoAjax(" . $this->resultado[$i]['cod_empresa'] . "," . $this->resultado[$i]['cod_tamanho_produto'] . ",'" . $this->resultado[$i]['razao_social'] . "','" . $this->resultado[$i]['nome'] . "','" . $this->resultado[$i]['tamanho'] . "'," . $preco . ")\"> ";
                            echo "<input type='text' style='visibility: hidden;' size='2' maxlength='2' value='1' id='quantidade_" . $this->resultado[$i]['cod_empresa'] . "_" . $this->resultado[$i]['cod_tamanho_produto'] . "'>";
                        }

                        $i++;
                    }

                    $i--;
                }
                ?>

            </div> <!-- precos -->



        </div>


        <?php
    }
    ?>

    <script>

        recebeCarrinhoJSON();


    </script>

